version: "3.7"
services:
  rover:
    image: massimilianolapuma/aws-rover:v1.0
    user: vscode

    labels:
      - "caf=AWS CAF"

    volumes:
      - ..:/tf/caf
      - volume-caf-vscode:/home/vscode
      - volume-caf-vscode-bashhistory:/commandhistory
      - ~/.ssh:/tmp/.ssh-localhost:ro

      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - HISTFILE=/commandhistory/.bash_history
      - HISTSIZE=1000

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  volume-caf-vscode:
    labels:
      - "caf=AWS CAF"
  volume-caf-vscode-bashhistory: