name: Build Rover ci images

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the rover
      run: |
        set -e
        sudo docker login -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }} ${{ secrets.registry_url }}
        # Build the rover base image
        make ci